### ISSUE TITLE
How to make this work?

### ISSUE THREAD

**Issue by goldsky** [Jako/LangRouter#1]
I've changed the plugin code to

``` php
return include MODX_CORE_PATH . 'components/langrouter/elements/plugins/langrouter.plugin.php';
```

just to catch error's line, and this is my FATAL error in front-end:

```
Fatal error: Call to a member function getOption() on a non-object in D:\localhost\modx-revo-babel\2.3\core\components\langrouter\elements\plugins\langrouter.plugin.php on line 141
```

And this log in error log:

```
[2015-02-14 00:49:46] (ERROR @ /modx-revo-babel/2.3/index.php) Could not prepare context: en
```

I've read the readme, and I've set these as well:
- base_url : `/`
- site_url : `http://localhost/modx-revo-babel/2.3/en/`

I used MODX's original .htaccess, with this common adjustment for my localhost:

``` sh
RewriteEngine On
RewriteBase /modx-revo-babel/2.3/
```

other than that stayed intact.

So, how to make this work?

**Comment by Jako** [comment]
$modx->context is not set in line [142](https://github.com/Jako/LangRouter/blob/master/core/components/langrouter/elements/plugins/langrouter.plugin.php#L142)

The message `Could not prepare context: en` is strange (not a LangRouter message). It should be generated in line [138](https://github.com/Jako/LangRouter/blob/master/core/components/langrouter/elements/plugins/langrouter.plugin.php#L138). But $switched should be false then. Maybe a MODX bug.

**Comment by Jako** [comment]
Maybe you have no context `en` and you are using the default `web` context for that. So the error occurs in [121](https://github.com/Jako/LangRouter/blob/master/core/components/langrouter/elements/plugins/langrouter.plugin.php#L121). Have no time at the moment to look for a solution then, sorry.

Susan has posted a possible but not universal solution in comments for https://gist.github.com/gadamiak/3812853

**Comment by Jako** [comment]
Have you solved this?

**Comment by vierkantemeter** [comment]
I have these errors too. I have 3 contexts:
- web
- en
- de

MODX installed in the webroot, so no subfolder-system which can mess up langrouter. Babel set up using http://designfromwithin.com/blog/modx-multilingual

My settings:

babel.contextDefault = web
All contexts: base_url: /
and site_url: {server_protocol}://{http_host}{base_url}{cultureKey}/

I guess I'm using a pretty common setup, so Langrouter should work, I guess. Can you tell me if there is a fix for this? Sotwotell's solution you have suggested does not work (anymore).

MODX 2.3.3
Babel 3.0.0-b3
Langrouter 1.0.0

**Comment by Jako** [comment]
Could you first set babel.contextDefault to one language. Or is 'web' needed somehow?

**Comment by vierkantemeter** [comment]
Thanks for your reply! Hmm, this is confusing. In your setup guide you are saying:

> "Add new system setting babel.contextDefault and set it to the default context"

This suggests that the contextKey needs to be set (default 'web' in my case which name can't be changed). But you mean to set the value of cultureKey instead?

I tried to set this (nl), but still get the errors like @goldsky mentioned (`Could not prepare context: nl` and `Call to a member function getOption() on a non-object in..`

Is it intended that you don't use the web context, and create new contexts for all languages?

If like to take a peek at my install, you're welcome. Let me know.

**Comment by Jako** [comment]
Sorry, the docs and most of the code are done by gadamiak, but he does not maintain the code anymore.

`web` should not be the problem, since the code switches the context to web if babel.contextDefault is not set.

I don't know why your context is not ready to prepare. Could be a missing security setting/access policy as Mark mentioned here: http://stackoverflow.com/questions/9761447/modx-revolution-doesnt-switch-context

**Comment by vierkantemeter** [comment]
Thanks Jako. Going to experiment some more. If I find a solution, I'll post it here.

**Comment by Jako** [comment]
Ask @goldsky about that, he has solved it (according to a Twitter answer).

**Comment by Jako** [comment]
@vierkantemeter Try the latest version from the MODX repository. The system setting babel.defaultContext is requested/set during installation. There should be no issues with not set $modx->context in the plugin anymore.

**Comment by goldsky** [comment]
The problem relies on this:

```
$modx->switchContext($reqCultureKey);
```

line 123
This mixes up between **context key** and **culture key**.

Nasty solution is by replacing it with

```
$modx->switchContext($reqCultureKey === 'en' ? 'web' : $reqCultureKey);
```

**Comment by Jako** [comment]
@goldsky Thanks for mentioning again, it is fixed now.
