### ISSUE TITLE
Possible duplicated content.

### ISSUE THREAD

**Issue by ysanmiguel** [Jako/LangRouter#24]
Hello mate.
It's possible to access to the main context via `/` and `/cultureKey/` creating two different addresses to get to the same point. 

`domain.com/ `          **and**     `domain.com/en/`     
or
`domain.com/page-four.html `          **and**     `domain.com/en/page-four.html`     
will open the same page  without changing the address.

I think (unless I'm wrong) that is duplicated content and might be penalised by SEO rules.
should be redirected via **301** to one or the other all the time.

Cheers.

**Comment by Jako** [comment]
Could you post your context settings of the different language contexts?

**Comment by ysanmiguel** [comment]
Here they are:

**Context = web (default)**
base_url: /
cultureKey: en
http_host: domain.com
site_start: 1
site_ur: {url_scheme}{http_host}{base_url}{cultureKey}/

**Context = es**
base_url: /
cultureKey: es
http_host: domain.com
site_start: 7
site_ur: {url_scheme}{http_host}{base_url}{cultureKey}/

**Comment by Jako** [comment]
I have tested your config and it seems that {cultureKey} is not replaced in the site_url context setting. That could have caused the other issues, since there is only one site_url for every context now.
