### ISSUE TITLE
routing problem to homepages 

### ISSUE THREAD

**Issue by degoya** [Jako/LangRouter#25]
# Setup
Modx 2.72, Babel 3.0.0 and LangRouter 1.3.3 

# Problem
I've setup a multilang website with babel and langrouter, i followed the installation guide. but when i go to the doman i will get redirected to domain.local/de instead of domain.local/de/ . so the last slash is missing and i get a 404 page instead of the start page (thats a correct behaviour because rhe resource de is not existing). With a rightclick view in the manager i get the same result when i show the homepage of each context, all other resources get redirected correct. 

After i've moved the site from windows to a mac i was not able to reproduce the error. Then i moved it to a debian webserver and it was still working. Moving it to another Windows machine brings up the error again. i think that is a windows problem. i've got another site with modx 2.65, Babel and Langrouter 1.3.0 and this works without any problems on Windows. Dunno if it's modx 2.72 or Langrouter who causes that error.

# Debug Log when entering domain.local/en/
`
[2020-02-13 19:10:59] (ERROR in LangRouter @ website\src\web\core\components\langrouter\model\langrouter\langrouter.class.php : 158) Unhandled request:
REQUEST_URI:   /en
REDIRECT_URI:  
QUERY_STRING:  q=en
q:             en
Context:       de
Site start:    9
[2020-02-13 19:10:59] (ERROR in LangRouter @ website\src\web\core\components\langrouter\model\langrouter\langrouter.class.php : 175) contextmap: array(2) {
  ["de"]=>
  string(2) "de"
  ["en"]=>
  string(2) "en"
}
[2020-02-13 19:10:59] (ERROR in LangRouter @ website\src\web\core\components\langrouter\model\langrouter\langrouter.class.php : 158) Culture key found in URI:
REQUEST_URI:   /en
REDIRECT_URI:  
QUERY_STRING:  q=en
q:             en
Context:       en
Site start:    1
`

**Comment by Jako** [comment]
It redirects to the url thats contained in the context setting 'site_url'. So you have to make clear, that this setting is set right.

I will take a look, how to deal with those cultureKey based urls, not having a trailing slash, in LangRouter.

**Comment by degoya** [comment]
here are screens for both context settings 

![grafik](https://user-images.githubusercontent.com/3515182/74518460-2e1fd600-4f14-11ea-8f22-de35ee15ca04.png)

![grafik](https://user-images.githubusercontent.com/3515182/74518506-3f68e280-4f14-11ea-9973-55c16ac8e075.png)

**Comment by Jako** [comment]
Could you check, if this is solved with LangRouter 1.3.4?

**Comment by degoya** [comment]
it seems the problem is solved with the latest update.

**Comment by degoya** [comment]
i've just double checked in the local MAMP test setup and still got the same problem with the routing

**Comment by Jako** [comment]
Could you check with a remote debugger, where the redirect to the url with the not trailing slash occurs. Is it inside of LangRouter?
