### ISSUE TITLE
site_status issues

### ISSUE THREAD

**Issue by jcamachott** [Jako/LangRouter#3]
Hi, I hope you can help me out.

MODX Revo 2.5
Babel 3.0.0-rc1
LangRouter 1.0.6-pl

site_status is set to No, in default System Settings and also context settings for both 'en' and 'fr' contexts.

Visitors to http://domain.com/ are still seeing the english front page! (tested on other computers).
Visitors to http://domain.com/en are getting the Site unavailable message.
Visitors to http://domain.com/en/ (notice the slash) are seeing the english front page.

Same for fr (but with french front page as expected)

How? Why?

I have to workaround this by creating a snippet that checks the SCRIPT_URI so both http://domain.com/ and http://domain.com/en/ redirect to http://domain.com/en

Any ideas how this can be fixed without the snippet?

Thanks!

**Comment by Jako** [comment]
Look for the `site_unavailable_page`. Is it published? Same with `error_page` and `unauthorized_page`. MODX tries to serve one of those resources.

**Comment by jcamachott** [comment]
thanks for responding!

**site_unavailable_page** is set to 0 and **site_unavailable_message** is what's displayed for http://domain.com/en

Both **error_page** and **unauthorized_page** point to a resource that is published but it is not displayed

**Comment by Jako** [comment]
Hmm, I have never tested what happens in LangRouter when site_status is set to 0. It should redirect then too, but I have to debug & test this.

**Comment by jcamachott** [comment]
Sure, no problem. At least I have a workaround.
