### ISSUE TITLE
Compatibility with debugParser

### ISSUE THREAD

**Issue by zaigham** [Jako/LangRouter#4]
When using LangRouter, I am unable to use debugParser unless I set the LangRouter plugin priority to 1.

Not sure if its a bug, or some race condition.

**Comment by Jako** [comment]
Could you try to add a return; in the last line of the LangRouter plugin?

**Comment by zaigham** [comment]
Removed the priority and added `return;` at the end of plugin code. Seems to work now.

**Comment by Jako** [comment]
Thanks for the message.
