### ISSUE TITLE
Errors using LangRouter

### ISSUE THREAD

**Issue by DonQuicky** [Jako/LangRouter#9]
I have installed latest version of LangRouter 1.1.3-pl on MODX 2.5.2 with Babel 3.0.0-rc1.

I am using two contexts: web and english (en as context key). When switching to view my site with English agent I notice that the tag <base> is not showing the en cultureKey. The language still remains default.

My <base> code in the template is:

`<base href="[[!++site_url]]">`

In the system settings the option for logging is turned on.  In the error log I do notice this error:

`[2016-12-06 16:02:35] (ERROR in LangRouter @ /home/deb75895n2/domains/codeplaza.com/public_html/ontwikkel/core/components/langrouter/model/langrouter/langrouter.class.php : 148) Unhandled request:
REQUEST_URI:   /portfolio/
REDIRECT_URI:  
QUERY_STRING:  q=portfolio/
q:             portfolio/
Context:       web
Site start:    1
[2016-12-06 16:02:35] (ERROR in LangRouter @ /home/deb75895n2/domains/codeplaza.com/public_html/ontwikkel/core/components/langrouter/model/langrouter/langrouter.class.php : 165) contextmap: array(0) {
}

[2016-12-06 16:02:35] (ERROR in LangRouter @ /home/deb75895n2/domains/codeplaza.com/public_html/ontwikkel/core/components/langrouter/model/langrouter/langrouter.class.php : 165) Default context key: string(3) "web"

[2016-12-06 16:02:35] (ERROR in LangRouter @ /home/deb75895n2/domains/codeplaza.com/public_html/ontwikkel/core/components/langrouter/model/langrouter/langrouter.class.php : 148) Culture key not found in URI:
REQUEST_URI:   /portfolio/
REDIRECT_URI:  
QUERY_STRING:  q=portfolio/
q:             portfolio/
Context:       web
Site start:    1
[2016-12-06 16:02:35] (ERROR in LangRouter @ /home/deb75895n2/domains/codeplaza.com/public_html/ontwikkel/core/components/langrouter/model/langrouter/langrouter.class.php : 177) Context switch to "web" was not valid.`

What could be wrong?

**Comment by Jako** [comment]
Are the context settings of the web context set according to http://jako.github.io/LangRouter/usage/ ?

**Comment by DonQuicky** [comment]
Yep, I believe so.

context: Website
context_key: web
base_url: /
site_url: {url_scheme}{http_host}{base_url}{cultureKey}/

context: English
context_key: en
base_url: /
site_url: {url_scheme}{http_host}{base_url}{cultureKey}/

**System setting:**
babel.contextDefault: web
babel.contextKeys: web,en

**Template:**
`<base href="[[!++site_url]]">`

**Comment by Jako** [comment]
Does web have a cultureKey setting?

**Comment by DonQuicky** [comment]
I have set the cultureKey setting as **nl** in the system settings which I believe will be used as default also for web.

**Comment by Jako** [comment]
I think it has to be a context setting, because the placeholders in site_url context setting are replaced only with context settings.

**Comment by DonQuicky** [comment]
I added the context key culture_key to default context web and also had to add the site_start key to both contexts and voila ... now it's working fine.

So it seems that switching between contexts the default settings for web are ignored as context keys.

**Comment by Jako** [comment]
Yes, maybe it could be implemented.

**Comment by Jako** [comment]
It could be done with https://github.com/Jako/LangRouter/commit/6ba11ab039b495db630a67c8ec3720750905ac7b but I am not sure to implement that in the main version.
